---
- hosts: localhost

  tasks:
  - name: Create Operator users in ManageIQ
    with_items: "{{ groups['operators'] }}"
    manageiq_user:
      name: "{{ item }}"
      state: 'present'
      fullname: "{{ hostvars[item].full_name }}"
      password: "{{ hostvars[item].password }}"
      group: "{{ hostvars[item].group }}"
      # TODO (dkorn): consider using env vars
      miq_url: 'http://localhost:3000'
      miq_username: 'admin'
      miq_password: 'smartvm'
      # TODO (dkorn): will probavly verify SSL
      verify_ssl: False
    # TODO (dkorn): remove if no debug
    register: result

  # TODO (dkorn): decide if the printing the results is needed
  - debug: var=result

  - name: Add Amazon EC2 Provider to ManageIQ
    with_items: "{{ groups['amazon_providers'] }}"
    manageiq_provider:
      name: "{{ item }}"
      state: 'present'
      provider_type: "{{ hostvars[item].type }}"
      provider_region: "{{ hostvars[item].region }}"
      access_key_id: "{{ hostvars[item].access_key_id }}"
      secret_access_key: "{{ hostvars[item].secret_access_key }}"
      miq_url: 'http://localhost:3000'
      miq_username: 'admin'
      miq_password: 'smartvm'
      verify_ssl: False
    register: result

  - debug: var=result

  - name: Add Openshift Containers Providers to ManageIQ
    with_items: "{{ groups['openshift_providers'] }}"
    manageiq_provider:
      name: "{{ item }}"
      provider_type: "{{ hostvars[item].type }}"
      state: 'present'
      zone: "{{ hostvars[item].zone }}"
      provider_api_hostname: "{{ hostvars[item].hostname }}"
      provider_api_port: "{{ hostvars[item].port }}"
      provider_api_auth_token: "{{ hostvars[item].token }}"
      metrics: "{{ hostvars[item].metrics }}"
      hawkular_hostname: "{{ hostvars[item].hawkular_hostname }}"
      hawkular_port: "{{ hostvars[item].hawkular_port }}"
      miq_url: 'http://localhost:3000'
      miq_username: 'admin'
      miq_password: 'smartvm'
      verify_ssl: False
    register: result

  - debug: var=result
